<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE Goods[
<!ELEMENT Goods (Good+)>
<!ELEMENT Good (GoodID, Info)>
<!ELEMENT Info (BasicInfo, Comments)>
<!ELEMENT BasicInfo (Name, Description, Label, Price, SellerName)>
<!ELEMENT Comments (Comment+)>
<!ELEMENT Comment (BuyerName, Stars, Content)>
<!ELEMENT GoodID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Label (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ELEMENT SellerName (#PCDATA)>
<!ELEMENT BuyerName (#PCDATA)>
<!ELEMENT Stars (#PCDATA)>
<!ELEMENT Content (#PCDATA)> ]>
<XML>
    <Goods>
        <Good>
            <GoodID>4</GoodID>
            <Info>
                <BasicInfo>
                    <Name>compiler</Name>
                    <Description>二手二手包邮 龙书 编译原理 第2版</Description>
                    <Label>book</Label>
                    <Price>32.5</Price>
                    <SellerName>trinity</SellerName>
                </BasicInfo>
                <Comments>
                </Comments>
            </Info>
        </Good>
    </Goods>
</XML>
